version: '3.1'
services:
  web:
    image: tms/odoo:0.2
    build:
      dockerfile: Dockerfile
    entrypoint: [ 
      '/bin/sh', 
      '-c', 
      './odoo-bin -d tms_dev -r odoo --db_host db --db_port 5432 -w "$$(cat /var/run/secrets/postgresql_password)" --config /etc/odoo/odoo.conf',
    ]    
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./docker/config:/etc/odoo
      - ./addons:/app/addons
      - ./addons-extra:/app/addons-extra
      - odoo-web-data:/var/lib/odoo
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: .odoo_pg_pass
